### ISSUE TITLE
Regarding the note about the bug

### ISSUE THREAD

**Issue by SleeplessOne1917** [thomasdouwes/lemmy-flagwaver-bot#5]
It should be fixed in version 0.4.1 and above in the lemmy-bot library. See if updating the dependency fixes the issue for you.

**Comment by thomasdouwes** [comment]
Do you mean the bug on this project or the issue I opened on lemmy-bot? I got your reply on that issue and I'll test it

**Comment by thomasdouwes** [comment]
Oh the bug in the README?

**Comment by SleeplessOne1917** [comment]
The bug in the README.

**Comment by thomasdouwes** [comment]
I can't get 0.4.1 working with lemmy 0.17.4. I'll change the note to mention that the bug is fixed but this project is still using an older version for compatibility with 0.17.4.

**Comment by thomasdouwes** [comment]
I have updated the README and added a 0.18.0 branch that used the new version of lemmy-bot

**Comment by thomasdouwes** [comment]
I changed the README for 0.18.0 so I will close this now
